import IUser from './IUser';
import ISender from './ISender';
import IResponsable from './IResponsable';
import IUserV from './IUserV';
import Description from './Description';
import Message from './Message';
import Comment from './Comment';
import Dialogue from './Dialogue';
import Effect from './Effect';
import Event from './Event';
import Job from './Job';
import Like from './Like';
import Location from './Location';
import Tag from './Tag';
import Team from './Team';
import Token from './Token';
import User from './User';
import Work from './Work';
import Business from './Business';
import Branch from './Branch';
import Category from './Category';
import Subcategory from './Subcategory';
import Service from './Service';
import Workdesk from './Workdesk';
import WorkingHours from './WorkingHours';

export default [IUser, ISender, IResponsable, IUserV, Description, Comment, Message, Dialogue, Effect, Event, Job, Like, Location, Tag, Team, Token, User, Work, Business, Branch, Category, Subcategory, Service, Workdesk, WorkingHours];